import './styles/story-image-integrity.css';
import './styles/pbe-publication-unify.css';
import './styles/pbe-header-polish.css';
import './styles/background-selector.css';
import './styles/background-selector-overlay-fix.css';
import './styles/pbe-personalization-polish.css';
import './styles/pbe-header-league-group.css';
import './styles/pbe-scene-preview-fix.css';
import './styles/pbe-background-assets.css';
import './styles/pbe-intelligence-graph.css';
import { initBackgroundSelector } from './background-selector.js';
import { initNflLaunchPriority } from './nfl-launch-priority.js';
import { initSiteEnhancements } from './site-enhancements.js';
import { initStoryMediaBackfill } from './media-backfill.js';
import { initArticleTrustLayer } from './article-trust.js';
import { initArticleFunnel } from './article-funnel.js';
import { initAnalytics } from './analytics.js';
import { initRouter } from './router.js';

initBackgroundSelector();
initNflLaunchPriority();
initSiteEnhancements();
initStoryMediaBackfill();
initArticleTrustLayer();
initArticleFunnel();
initAnalytics();
initRouter();